### ISSUE TITLE
[azservicebus] Recreate the ATOM client using the autorest generator

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#17041]
The ATOM client in the azservicebus package was generated from an older client, and is not standardized like the rest of our autogenerated libraries (for instance, it has it's own "custom" retry policy, etc..).

We need to regenerate this, based on the swagger for the API. 

My first pass at this has shown that it does generate _some_ parts of the client correctly. This has been done in Python and Java, so this might be a case of some limitation of our current autorest generator.

Swagger link: [sb-swagger](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/sb_dataplane_namespace/specification/servicebus/data-plane/servicebus-swagger.json)

If the generation is correct, it should fix:
- [ ] #15972 (make pagers recreatable), 
- [ ] #15917 (add support for MaxMessageSizeInKilobytes)
- [ ] #16692 (missing fields in data models)
- [x] #16045 (manage subscription rules in the ATOM client)

**Comment by richardpark-msft** [comment]
At this point we're far past GA. Regenerating might have some utility now but it's far less needed than it would have been before. Closing for now.
