### ISSUE TITLE
Cosmos DB: SessionContainer

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-go#18987]
Add SessionContainer to help with accounts with Session Consistency.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/SessionContainer.cs
```[tasklist]
### Tasks
- [ ] Adding hashing support
- [ ] Add container properties cache (used to read the partition key path and apply hashing)
- [ ] Add partition key ranges cache (used to identify which partition the request goes to after applying hashing)
```

**Comment by jay-most** [comment]
Notes: Time 1-2 weeks | T-shirt S | add session token to the header response. session cache. same session reads and writes. in memory cache.
