### ISSUE TITLE
MQ: Automate Azure Identity SDK Manual/Vendor Tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#21118]
We should leverage @christothes 's work on https://github.com/Azure/azure-sdk-for-net/pull/33017/files to fully automate the list of manual/vendor test scenarios which are documented in the issues here: https://github.com/Azure/azure-sdk/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity

This includes:

- [ ] ~Automate Azure Arc testing~
- [ ] ~Automate Azure Identity multi tenant testing~
- [x] Automate Azure Container Instances testing #22652
- [ ] ~Automate Azure WebJobs testing~
- [ ] ~Automate Azure Service Fabric testing~
- [X] Automate Azure Functions testing #22562
- [x] Automate VM MSI testing #22517
- [x] Automate Workload Identity testing #22627
- [ ] ~Automate Pod Identity testing~ deprecated
- [ ] ~Automate Cloudshell testing~
