### ISSUE TITLE
Ship Azure Identity Preview 1

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-for-go#6505]
- [x] Add UsernamePassword Credential #6434 
- [x] Add Device Code Credential #6433
- [x] Identity Arch Review fixes #6506

**Comment by catalinaperalta** [comment]
Closing this for now. Feel free to re-open if not complete. The alpha release was made with tag `sdk/azidentity/v0.1.0`.
