### ISSUE TITLE
Create an Amazing Dev-time Credential Experience for Azure.Identity

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#6602]
Tracking issue for feature work specific to Developer-time Azure.Identity Credential Experience

- [ ] Bring back file based auth for Management Plane: https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth AZURE_AUTH_LOCATION (see https://github.com/Azure/azure-sdk-for-net/pull/9312) (@ellismg driving design requirements)

- [ ] Add Support for writing back to the SharedTokenCache (@schaabs driving design requirements)

- [ ] Add Linux and Mac SharedTokenCache Support (@jianghaolu driving design requirements)

- [x] Improve DefaultAzureCredential/ChainedTokenCredential - e.g., tell me what Credential I'm using for dev debug scenarios (@catalinaperalta driving design requirements)

- [x] Have ManagedIdentityCredential utilize the AZURE_CLIENT_ID environment variable. To allow user assigned identities to utilize DefaultAzureCredential (@jongio driving implementation with vendor team)

- [x] Have TokenCredentialOptions utilize AZURE_AUTHORITY_HOST environment variable.  To allow other clouds to use DefaultAzureCredential. (@jongio driving implementation with vendor team)

- [x] CliCredentials / Better support for dev creds: CLI, PSH, VS, VS CODE, VS ONLINE, CLOUD SHELL
   - devCredentials (@schaabs driving design requirements)
   - CliCredential (@jongio driving implementation with vendor team)

**Comment by chlowell** [comment]
Closing this as complete, we've either implemented or decided not to implement each item

**Comment by chlowell** [comment]
Are you interested in a particular item? Of the ones above, these are implemented:
- authentication via Azure CLI, Cloud Shell
- better error messages for DefaultAzureCredential and ChainedTokenCredential
- credentials observe AZURE_AUTHORITY_HOST

**Comment by weinong** [comment]
@chlowell we need token cache support for interactive browser credential. Is it implemented?

**Comment by chlowell** [comment]
Depends on the sort of cache you want. That credential has an in-memory cache today. We plan to add an optional persistent cache but have no ETA for that.

**Comment by weinong** [comment]
any chance to accelerate that? i'm the maintainer of https://github.com/Azure/kubelogin which is a client side tool just like az cli. in memory cache will not help

**Comment by chlowell** [comment]
I really don't know when we could ship persistent caching. We're waiting on https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/58. I'll take your comment as a vote for increasing its priority and pass it along to the MSAL team (feel free to comment on the MSAL issue as well). I expect they will still want to implement their current high priority features first though.

**Comment by weinong** [comment]
should we open an issue for this particular feature?

**Comment by chlowell** [comment]
We're already tracking it with #16643
